# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - eduquest-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://eduquestfrontend.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e67e16bb09ff4d22988c0eac0426d402 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6b2acf4a4334426fb056244f848ab94b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: eduquestfrontend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e67e16bb09ff4d22988c0eac0426d402 }}/eduquestfrontend/eduquest-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'eduquest-frontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4362e3c92e6e4d65aab9ebddbf19b4a2 }}
        images: 'eduquestfrontend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e67e16bb09ff4d22988c0eac0426d402 }}/eduquestfrontend/eduquest-frontend:${{ github.sha }}'